#!/usr/bin/env python3
"""
DELULUREEL BYOC Test  ·  https://delulureel.com/byoc
──────────────────────────────────────────────────────
Verifies that your local ComfyUI is compatible with
DELULUREEL Studio before subscribing to the BYOC plan.

DATA sent to delulureel.com
  • Your GPU name and available VRAM
  • Names (filenames) of the AI models in ComfyUI
  • Your email address
  • The 512×512 test image generated by ComfyUI

DATA that never leaves your machine
  • Model weights or any model content
  • Config files or personal documents
  • Anything not listed above

Requirements  Python 3.8+  and  pip install requests
Usage         python byoc_test.py --email you@example.com
Source        https://github.com/ObiriecLabs/delulureel/blob/main/byoc_test.py
"""

import argparse, hashlib, sys, time

try:
    import requests
except ImportError:
    print("  Missing dependency: pip install requests")
    sys.exit(1)

SERVER   = "https://delulureel.com"
COMFY    = "http://localhost:8188"
TIMEOUT  = 10   # seconds for individual HTTP calls
POLL_INT = 3    # seconds between ComfyUI history polls
MAX_POLL = 120  # 6 minutes maximum wait

# ── Output helpers ─────────────────────────────────────────────────────────────

W = 56

def _hr():        print("  " + "─" * W)
def _ok(m):       print(f"      ✓  {m}")
def _info(m):     print(f"      •  {m}")
def _warn(m):     print(f"      ⚠  {m}")
def _call(m):     print(f"      →  {m}")

def _fail(m):
    print(f"\n  ✗  {m}\n")
    sys.exit(1)

def _step(n, title):
    print(f"\n  [{n}/7]  {title}")

# ── Network wrappers (every call is printed) ───────────────────────────────────

def _get(url, session, silent=False):
    if not silent:
        _call(f"GET  {url}")
    try:
        r = session.get(url, timeout=TIMEOUT)
        r.raise_for_status()
        return r
    except requests.exceptions.ConnectionError:
        _fail(f"Connection refused: {url}\n     Is ComfyUI running?")
    except requests.exceptions.Timeout:
        _fail(f"Request timed out: {url}")
    except requests.exceptions.HTTPError:
        _fail(f"HTTP {r.status_code} from {url}")


def _post(url, session, **kw):
    _call(f"POST {url}")
    try:
        r = session.post(url, timeout=30, **kw)
        r.raise_for_status()
        return r
    except requests.exceptions.ConnectionError:
        _fail(f"Connection refused: {url}")
    except requests.exceptions.HTTPError:
        _fail(f"HTTP {r.status_code} from {url}\n     {r.text[:300]}")


def _models(comfy, folder, session):
    try:
        r = session.get(f"{comfy}/models/{folder}", timeout=TIMEOUT)
        data = r.json()
        return data if isinstance(data, list) else []
    except Exception:
        return []


# ── Main ───────────────────────────────────────────────────────────────────────

def main():
    ap = argparse.ArgumentParser(
        description="DELULUREEL BYOC Hardware Test",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    ap.add_argument("--email",   required=True,
                    help="Your email address")
    ap.add_argument("--url",     default=COMFY,
                    help=f"ComfyUI base URL  (default: {COMFY})")
    ap.add_argument("--dry-run", action="store_true",
                    help="List every step without executing it")
    args = ap.parse_args()

    comfy = args.url.rstrip("/")

    print()
    print(f"  ┌{'─' * (W + 2)}┐")
    print(f"  │{'  DELULUREEL  ·  BYOC Hardware Test':^{W + 2}}│")
    print(f"  └{'─' * (W + 2)}┘")
    print()
    print(f"  ComfyUI  {comfy}")
    print(f"  Email    {args.email}")
    if args.dry_run:
        print(f"  Mode     DRY-RUN (no network calls)")
    print()
    _hr()
    print()
    print("  What this script sends to delulureel.com:")
    print("    GPU name · VRAM · model filenames · email · test image")
    print()
    print("  What stays on your machine:")
    print("    Model weights · config files · everything else")
    print()
    _hr()

    # ── Dry-run: only list steps ──────────────────────────────────────────────
    if args.dry_run:
        print()
        print("  Steps that would run:")
        steps = [
            f"GET  {comfy}/system_stats",
            f"GET  {comfy}/models/{{checkpoints|diffusion_models|text_encoders|vae}}",
            f"POST {SERVER}/byoc/test/start  →  session token + test workflow",
            f"POST {comfy}/prompt  (512×512, 10 steps)",
            f"GET  {comfy}/history/{{prompt_id}}  (every {POLL_INT}s)",
            f"GET  {comfy}/view?filename=...  →  download output",
            f"POST {SERVER}/byoc/test/finish  →  watermark + result link",
        ]
        for i, s in enumerate(steps, 1):
            print(f"    {i}. {s}")
        print()
        print("  Remove --dry-run to execute the test.")
        print()
        return

    sess = requests.Session()

    # ── 1. Connect to ComfyUI ─────────────────────────────────────────────────
    _step(1, "Connect to ComfyUI")
    stats = _get(f"{comfy}/system_stats", sess).json()
    sys_  = stats.get("system", {})
    gpu   = sys_.get("gpu_name") or sys_.get("device") or "Unknown GPU"
    vmb   = int(sys_.get("vram_total") or 0)
    vgb   = round(vmb / 1024, 1) if vmb else "N/A"
    _ok(f"GPU: {gpu}   VRAM: {vgb} GB")

    # ── 2. Read model list ────────────────────────────────────────────────────
    _step(2, "Read model list from ComfyUI")
    ckpt = _models(comfy, "checkpoints",      sess)
    diff = _models(comfy, "diffusion_models", sess)
    te   = _models(comfy, "text_encoders",    sess)
    vae  = _models(comfy, "vae",              sess)
    total = len(ckpt) + len(diff) + len(te) + len(vae)
    _ok(f"{total} models found  "
        f"(checkpoints:{len(ckpt)} diffusion:{len(diff)} "
        f"text_encoders:{len(te)} vae:{len(vae)})")
    if total == 0:
        _warn("No models found. Install at least one SDXL checkpoint or FLUX files.")

    # ── 3. Register test session ──────────────────────────────────────────────
    _step(3, "Register test session with delulureel.com")
    _info(f"Sending to {SERVER}: gpu_name, vram_total_mb, model names, email")
    r3 = _post(f"{SERVER}/byoc/test/start", sess, json={
        "email":            args.email,
        "gpu_name":         gpu,
        "vram_total_mb":    vmb,
        "checkpoints":      ckpt,
        "diffusion_models": diff,
        "text_encoders":    te,
        "vae":              vae,
    })
    d3 = r3.json()
    if d3.get("error"):
        _fail(d3["error"])
    token    = d3["token"]
    workflow = d3["workflow"]
    wf_id    = d3.get("workflow_id", "?")
    _ok(f"Token: {token[:8]}…   Workflow: {wf_id}")

    # ── 4. Submit workflow to ComfyUI ─────────────────────────────────────────
    _step(4, "Submit test workflow to ComfyUI")
    _info("512×512 image · 10 steps · seed from server · no prompt text")
    r4 = _post(f"{comfy}/prompt", sess, json={"prompt": workflow})
    prompt_id = r4.json()["prompt_id"]
    _ok(f"prompt_id: {prompt_id[:8]}…")

    # ── 5. Poll for completion ────────────────────────────────────────────────
    _step(5, f"Wait for generation  (polling {comfy}/history/{prompt_id[:8]}…)")
    outputs = None
    for i in range(MAX_POLL):
        time.sleep(POLL_INT)
        elapsed = (i + 1) * POLL_INT
        dots = "·" * ((i % 4) + 1)
        print(f"\r      {dots:<5} {elapsed}s elapsed   ", end="", flush=True)
        try:
            hist  = sess.get(f"{comfy}/history/{prompt_id}", timeout=TIMEOUT).json()
            entry = hist.get(prompt_id, {})
            st    = entry.get("status", {})
            if st.get("status_str") == "error":
                print()
                _fail("ComfyUI reported an error. Check its console for details.")
            if st.get("completed"):
                outputs = entry.get("outputs", {})
                break
        except Exception:
            pass
    print()
    if not outputs:
        _fail(f"Timeout after {MAX_POLL * POLL_INT // 60} min. "
              "Generation took too long — try again or check ComfyUI.")
    _ok(f"Generation complete  ({(i + 1) * POLL_INT}s)")

    # ── 6. Download generated file ────────────────────────────────────────────
    _step(6, "Download generated file from ComfyUI")
    blob, fname = None, "output.png"
    for node_out in outputs.values():
        for img in (node_out.get("images") or []):
            p = f"filename={img['filename']}&type=output"
            if img.get("subfolder"):
                p += f"&subfolder={img['subfolder']}"
            r6   = _get(f"{comfy}/view?{p}", sess)
            blob  = r6.content
            fname = img["filename"]
            break
        if blob:
            break
    if not blob:
        _fail("No output file found in ComfyUI history.")
    sha = hashlib.sha256(blob).hexdigest()[:16]
    _ok(f"{fname}   {len(blob) // 1024} KB   sha256:{sha}…")

    # ── 7. Upload to delulureel.com ───────────────────────────────────────────
    _step(7, "Upload result to delulureel.com")
    _info(f"Sending to {SERVER}: session token + image file only")
    _info("Server applies a test watermark and returns the public link")
    r7 = _post(f"{SERVER}/byoc/test/finish", sess,
               data={"token": token},
               files={"file": (fname, blob, "image/png")})
    d7 = r7.json()
    if d7.get("error"):
        _fail(d7["error"])
    _ok("Upload complete · watermark applied")

    # ── Result ────────────────────────────────────────────────────────────────
    print()
    _hr()
    print()
    print("  ✅  TEST PASSED — your hardware is DELULUREEL-compatible!")
    print()
    print(f"  Result:    {SERVER}/byoc/test/result/{token}")
    print(f"  Subscribe: {SERVER}/auth/signup?plan=byoc&email={args.email}")
    print()
    _hr()
    print()


if __name__ == "__main__":
    main()
